### ISSUE TITLE
No "Add to anki" button

### ISSUE THREAD

**Issue by ATEBEXE** [Ajatt-Tools/anki.koplugin#11]
The addon is installed but there's no "Add to anki" button,  I've tried reinstalling but to no avail.
Device: ONYX BOOX VOLTA3
![photo_2_2023-10-13_17-26-04](https://github.com/Ajatt-Tools/anki.koplugin/assets/38757888/151beb8c-0567-46a1-bd13-3198c7c5b5bb)
![photo_1_2023-10-13_17-26-04](https://github.com/Ajatt-Tools/anki.koplugin/assets/38757888/f13919ba-6f5a-4096-ab3b-02b8f7257c6b)

**Comment by nairyosangha** [comment]
Could you post your crash.log? (see https://github.com/koreader/koreader/wiki/Report-a-bug#required-information) 
You might be missing a config option, the addon will not load in that case

**Comment by ATEBEXE** [comment]
I`ve tried reinstalling Koreader and the addon again and for some reason everything have started working. I guess the problem was in the config.

**Comment by nairyosangha** [comment]
By the way, I can't help but notice those Chinese glyphs in your Japanese dictionary.
KOreader prefers Chinese over Japanese glyphs by default, but you can force it to render the text properly. You can add `ifo_lang=ja-ja` in the dictionary's .ifo file which should fix it, provided your KOReader version is new enough

note the 言 radical
![image](https://github.com/Ajatt-Tools/anki.koplugin/assets/34285115/3c359a5a-0724-4134-bc39-cda7011b553c)
