### ISSUE TITLE
Cannot synchronize note because it's empty

### ISSUE THREAD

**Issue by AlejandroGomezFrieiro** [Ajatt-Tools/anki.koplugin#21]
Currently using a Korean dictionary, and when I try to generate a note for Anki it says it cannot sync because the note is empty. Tried both in localhost (Ubuntu laptop) and koreader within Kindle using the same dictionary, and both give the same result.

Tested that notes are generated, for example, for English words without an available dictionary (but only stored offline, as it cannot figure out the language). When adding a dictionary, even English words fail with the same error.

**Comment by nairyosangha** [comment]
Someone had a similar issue a while back: https://github.com/Ajatt-Tools/anki.koplugin/issues/20#issuecomment-2024583500

If that's not it, I'll need to see your config.lua and a crash.log (verbose logging enabled)

**Comment by AlejandroGomezFrieiro** [comment]
Can report that I fixed on my end, it was an issue with conflicting template at origin and endpoint. Documentation should probably specific well that the template should match at both ends.

**Comment by nairyosangha** [comment]
I don't really get what you mean with 'conflicting template at origin and endpoint', but glad to hear it's fixed either way
