### ISSUE TITLE
[Feature Request] Support for Rikaitan-style pitch accent graphs

### ISSUE THREAD

**Issue by konomu** [Ajatt-Tools/anki.koplugin#23]
Rikaitan allows the creation of SVG pitch accent graphs when adding notes to Anki. It's described in this .js: https://github.com/Ajatt-Tools/rikaitan/blob/24.4.29.0/ext/js/display/pronunciation-generator.js

![image](https://github.com/Ajatt-Tools/anki.koplugin/assets/45617438/1bc9e7dc-7112-4095-a8fd-b88e0e50b20d)

I think these look better than the pitch accent graphs that the existing extension generates so I'd like to see this get implemented. It would also be ideal to implement an new output to a "Reading" field for the 'note' parameter so the new pitch accent graph can be displayed along side the reading of the word in hiragana.

![image](https://github.com/Ajatt-Tools/anki.koplugin/assets/45617438/72afd290-7dc2-41fb-bb98-77d4f4841bf3)

**Comment by tatsumoto-ren** [comment]
Shouldn't this be requested in [AJT Japanese](https://github.com/Ajatt-Tools/Japanese) instead the koreader plugin? For example when you make a card with goldendict or any other tool, you might still want to have the same style.

**Comment by konomu** [comment]
Personally, I stopped using the Japanese addon when I started using Yomichan. But you're right, I guess it would be better to implement it there instead of into this plugin.

**Comment by tatsumoto-ren** [comment]
Pitch accent graphs were added to AJT Japanese https://freesoftwareextremist.com/notice/AiaUHnDSblBKaDAZGK 

They don't look the same as pitch accent graphs in Rikaitan, they are way better.
