### ISSUE TITLE
Constant Crashing When Trying To Add Greek Words

### ISSUE THREAD

**Issue by squishygian** [Ajatt-Tools/anki.koplugin#24]
Hello my friend,

Unfortunately I've been having issues again,this time with an ancient Greek dictionary, sometimes it works but about 6/10 times it crashes, and I'm confused because there seems to be no constant   that stands out so I can determine why it's crashing for a particular word but not for another, anyway I've attached some of the crash logs which are usually some variation of this:

![Screenshot_20240508-155059](https://github.com/Ajatt-Tools/anki.koplugin/assets/103234885/d4423d48-8543-43ae-8853-867bd9c4b0b4)

![Screenshot_20240508-155031](https://github.com/Ajatt-Tools/anki.koplugin/assets/103234885/57f9a7ff-b350-44c8-aed3-e011fbfbd05e)

![Screenshot_20240508-155008](https://github.com/Ajatt-Tools/anki.koplugin/assets/103234885/1739e78f-5f19-4d2b-a1cc-2cd34502a159)

**Comment by squishygian** [comment]
I seem to have found the issue, the document was a .docx file, I converted it to PDF and now it works fine now!

**Comment by nairyosangha** [comment]
Hello again

just FYI, none of these crash logs actually tell me anything, you'd need to find the actual crash.log file that's generated by KOreader and send me that instead.
I wasn't aware you could open word documents with koreader, I tested it and it seems to work fine for me, so I'm curious what's actually wrong here

Although if just converting it to PDF does the trick as well you might as well call it a day and just read it like that :smile:
