### ISSUE TITLE
Change in config.lua breaks the plugin and user patch doesn't work.

### ISSUE THREAD

**Issue by SalomoDavidson** [Ajatt-Tools/anki.koplugin#25]
Hi! 
When I change the settings in the config.lua, the plugin doesn't give me the option add to Anki anymore, but it shows add to vocabulary builder. Also user patch doesn't work for me.
Thanks in advance for helping me out :)

**Comment by SalomoDavidson** [comment]
With changing the settings in the config I mean change the word_field, context_field etc.

**Comment by nairyosangha** [comment]
Please provide the `crash.log` file created by KOreader.

`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

User patch isn't gonna work if the plugin failed to load, and vocabulary builder showing up (which is a separate plugin bundled with KOreader itself) is a good hint that we indeed did fail to load. Probably you messed something up in the config.lua file. The `crash.log` might tell us what's wrong.


I've had to ask for people to post their crash.log one too many times, so I've finally set up issue templates now :smile: 
This is the push I needed

**Comment by nairyosangha** [comment]
Do you remember what you changed, did you change the `word_field` while still having other notes stored locally on the device by any chance? This may be a bug. The plugin keeps track of the word field on locally stored notes to have a simple form of duplicate checking. However if that field's name changes it's not gonna find it on older notes and it would crash

**Comment by nairyosangha** [comment]
Can you try checking out the latest commit, that should hopefully fix your issue. I'm assuming OP had the same problem so I'll close this if you confirm it works for you

**Comment by Peance** [comment]
> Can you try checking out the latest commit, that should hopefully fix your issue. I'm assuming OP had the same problem so I'll close this if you confirm it works for you

I tested and it worked! Thank you so much!
