### ISSUE TITLE
Add kana reading to created note

### ISSUE THREAD

**Issue by oldmerkum** [Ajatt-Tools/anki.koplugin#26]
Plugin appears to work well for mining vocab from my old kindle.
However, I notice that only the kanji, english definition and sentence context are extracted.
I'd like to also get the kana reading of the word added to the note.
(Sorry, this is more like request than an issue)

**Comment by oldmerkum** [comment]
I was able to get the extension added. I initially forgot to to edit `kana_field = "<NAME OF FIELD ON CARD GOES HERE>"` causing koreader to crash when I attempted to add a word to anki. Had to delete the saved json where cards are locally stored on my kindle to get the anki plugin to load properly again after editing that since it would silently fail on koreader startup.

Now when I add a card to anki, the reading still doesn't get added.

I do see this being added to the Glossary field though. So the pattern seems correct for `"(.*)【.*】"`

```html
<div class="definition">
  <ol>
    <li dict="JMdict-ja-en">かよう【通う】
    <br>〘v5u・vi〙
    <br>1 to go to and from (a place); to go back and forth between; to run between (e.g. bus, train, etc.); to ply between.
    <br>2 to go to (school, work, etc.); to attend; to commute; to frequent.
    <br>3 to circulate (e.g. blood, electricity); to be communicated (e.g. thought).
    <br>→血が通う1・心が通う
    <br>4 to resemble.
    </li>
  </ol>
</div>
```

Does this need edited perhaps? `["JMdict Rev. 1.9"]` Maybe not since it correctly is adding kanji and definition...

This is the contents of `koreader/data/dict/JMdict Japanese-English dictionary/JMdict-ja-en/JMdict-ja-en.ifo`
```
StarDict's dict ifo file
version=3.0.0
bookname=JMdict-ja-en
wordcount=188380
idxfilesize=8347959
synwordcount=484272

lang=ja-en
```

**Comment by nairyosangha** [comment]
> since it would silently fail on koreader startup.

I'll do something about this one of these days.. problem is that it loads these notes the moment a user opens a document, and it'd be kinda weird to immediately show them a popup even if they didn't interact with the plugin yet at all

> I do see this being added to the Glossary field though. So the pattern seems correct for "(.*)【.*】"

The pattern indeed looks correct, the problem is that it runs this pattern on the headword, NOT the definition itself.
For JMdict the headword is probably just `通う` so it can't match anything on that.
You'll have to add it to the list after all:
```lua
 kana_pattern = { 
     -- key: dictionary name as displayed in KOreader (received from dictionary's .ifo file) 
     -- value: a table containing 2 entries: 
     -- 1) the dictionary field to look for the kana reading in (either 'word' or 'description') 
     -- 2) a pattern which should return the kana reading(s) (the pattern will be looked for multiple times!) 
     ["JMdict Rev. 1.9"] = {"definition", "<font color=\"green\">(.-)</font>"}, 
     ["JMdict-ja-en"] = {"definition",  "(.*)【.*】"},
 }, 
```

I believe something like that should work

**Comment by nairyosangha** [comment]
Also, maybe a bit late to mention this now, but there are anki addons you can use that do this as well, and they are quite a bit smarter than what you'd get with this extension on the koreader plugin side https://ankiweb.net/shared/info/1344485230

**Comment by oldmerkum** [comment]
Messed around with this a while. Think this got it working in config.lua
`enabled_extensions = {`
Need to explicitly enable extensions it seems.

**Comment by oldmerkum** [comment]
Thanks for suggestion on using an anki addon instead btw.
I keep discovering that centralizing a lot of things into anki is simpler (had a time trying to get frequency data in my lookups, then found anki has an addon for that as well)
