### ISSUE TITLE
[Feature Request] Being able to select my own context sentence

### ISSUE THREAD

**Issue by it0na72** [Ajatt-Tools/anki.koplugin#3]
Once again, thanks for this amazing script. I have noticed the script tends to only add the sentence the word is in until there's a comma or a dot.

Would it be possible to implement a system where you could highlight the whole context you would like to add in the note? Sometimes the sentence the word is, doesn't have enough context to remember it in the future while reviewing it.

Thanks in advance.

**Comment by nairyosangha** [comment]
This is something I've been meaning to do as well. Adding extra context shouldn't be too hard.
I'm not sure about letting the user highlight the text they want though, how would that work? You'd have to close the popup to select extra text, at which point you can't create a card anymore

I was thinking more along the lines of adding an extra option in the long-press menu:
![image](https://github.com/Ajatt-Tools/anki.koplugin/assets/34285115/2735c915-38b2-42b8-9c11-a7b871cff2c2)

Which would then show you the currently selected text, which the user can then add to:
![image](https://github.com/Ajatt-Tools/anki.koplugin/assets/34285115/e0e2fb1f-e63d-42f9-9baa-77f8a34f7898)

It would look a bit better than this of course, but you get the idea

**Comment by it0na72** [comment]
Your option does indeed look better than what I had in mind. Looking forward to seeing this released!

**Comment by nairyosangha** [comment]
https://github.com/Ajatt-Tools/anki.koplugin/tree/custom_context
There's a working implementation on the branch above. Gonna try it for a few days before I merge to master, to see if I run into problems.

This is what it ends up looking like:
You can delete/add either single characters or whole sentences, before or after the word you looked up.
![image](https://github.com/Ajatt-Tools/anki.koplugin/assets/34285115/6f9b9b1f-05d1-4b1d-b48f-6aa50daf9004)

**Comment by it0na72** [comment]
Thank you for this! Will take it for a spin and keep you updated.

**Comment by nairyosangha** [comment]
Made a few more changes:
 - When you add/remove a sentence on either end, it was keeping whatever character offset you might have already set. This felt kinda unintuitive so I made it reset the character count to 0 in that case
 e.g. you expand the context after the lookupword with 2 characters, then with 1 sentence. You'd end up with 1 sentence and 2 characters of extra content. Now it will just be 1 sentence.
- When you modify the content you looked up, that modified content would be lost.
e.g. you get a dict lookup with the expression '固唾を飲む' and you want to just look up '固唾', the 'を飲む' part would disappear

**Comment by nairyosangha** [comment]
Also, inituitively I want to use the buttons on the top/left to expand the prepended content, but that actually removes content, should I switch those around?

**Comment by it0na72** [comment]
> Also, intuitively I want to use the buttons on the top/left to expand the prepended content, but that actually removes content, should I switch those around?

So I tried it out and this was immediately what I noticed. It might be worth changing these buttons around if you have the time.

Regarding both the other updates, they sound really nice too. However, when I'm adding a card with custom context, the scroll bar is quite small to check if the context I added is correct. Would it be possible to make the window of the custom context update its size depending on the size of the custom context?

**Comment by nairyosangha** [comment]
> So I tried it out and this was immediately what I noticed. It might be worth changing these buttons around if you have the time.

Easy fix, will do

> Would it be possible to make the window of the custom context update its size depending on the size of the custom context?

Resizing on the fly is a pain to deal with, you have to do more repaints to have it render correctly, and (as far as I know) you have to manually calculate the amount of space your text will take, so I'd rather not right now.
I did set the size to 150px initially, I'll make it scale to half of the screen. That should get rid of the need to scroll in most cases.

> the scroll bar is quite small to check if the context I added is correct

You know you can tap anywhere on the text to make it scroll, right? :smile:

**Comment by it0na72** [comment]
Thank you for this, will update the script and keep you in touch!
