### ISSUE TITLE
Error while synchronizing note: cannot create note because it is empty

### ISSUE THREAD

**Issue by DigitalDraff** [Ajatt-Tools/anki.koplugin#32]
Kindle Paperwhite 11th
* KOReader version:  v2024.04

Dumb question but after following all the steps and successfully connecting with Anki-Connect, I can't add or sync anything because I "cannot create note because it is empty"???

![Reader_2024-08-05_003659](https://github.com/user-attachments/assets/cb341cf4-c918-4cdc-affa-d5e0f825ff45)

1. Select any word (spanish or english)
2. Click on `Dictionary`
3. Click on `Add to Anki`
4. See pop up:  "Error while synchronizing note: cannot create note because it is empty"
 
**crash.log**
08/05/24-00:36:58 INFO  Displaying popup with message: 'Error while synchronizing note:
cannot create note because it is empty' 
ffi.load: libs/liblodepng.so
08/05/24-00:38:04 INFO  (re)initializing context buffer with size: 50 
08/05/24-00:38:04 INFO  after reinit: prev table = 254, next table = 274 
08/05/24-00:38:04 INFO  AnkiNote#get_custom_context() 1 0 1 0 
08/05/24-00:38:05 INFO  AnkiConnect#post_request: code: 200, header: table: 0xb4622560, status: HTTP/1.1 200 OK

**Comment by nairyosangha** [comment]
> Error while synchronizing note: cannot create note because it is empty

Can you check whether the first field on your note is actually being populated? You cannot create an anki note if the first field on the note isn't filled in with something, it will throw that error, which is kinda misleading
