### ISSUE TITLE
Context lost with pdf files.

### ISSUE THREAD

**Issue by Surtr-sys** [Ajatt-Tools/anki.koplugin#34]
My koreader version is newest and my device is kobo clara hd, the plugin working just fine with epub files, but when it comes to pdf the context is lost.
![Uploading image.png…]()

**Comment by nairyosangha** [comment]
Your screenshot seems to be broken. 

I thought adding context was only supported for EPUB files (this functionality comes from KOreader itself) but apparently it should work on some PDFs as well, provided the text in it is actually selectable. Can you try again with the latest commit? https://github.com/Ajatt-Tools/anki.koplugin/commit/315ba7d714777661b34f86c83d309a055a9c3b4b

**Comment by Surtr-sys** [comment]
Thank for your hard work, now i could save the sentences with context, however it only works with custom context, If i press add to anki normally it will display could not connect to forvo, I have read the FAQ and change my document language but i don't know where to add the dictionary setting, sorry I am not much of a technical person.

**Comment by nairyosangha** [comment]
You don't have to modify the dictionary if you managed to change the language of the document. The fact you got the 'Could not connect to forvo' error already indicates you got past the language determination part. Did you try this multiple times? Sometimes forvo just has a hiccup and fails to get the audio, retrying it usually works. I've never seen it consistently fail over and over again

**Comment by Surtr-sys** [comment]
Thank you with your supportive feedback, this plugin has improved my workflow significantly. my best regards.
