### ISSUE TITLE
Everything suddenly disappear although i do not touch anything. 

### ISSUE THREAD

**Issue by Surtr-sys** [Ajatt-Tools/anki.koplugin#35]
Hi, is me again sorry to bother you once more, but In the process of my sentence mining, everything suddenly disappear, the add to anki button does not show up again even though I just used the plugin in the ereader as normal.
I have tried reinstall koreader and the plugin along way but it still not showing up, which is puzzle me the most. 
I have even factory reset the ereader and download the plugin package again.

**Comment by nairyosangha** [comment]
can you post your crash.log, instructions how to get that file are in the issue template

**Comment by Surtr-sys** [comment]
HI I check the config file again and realize I mess it up, the plugin's working now, very sorry for not checking it first. but I still don't know why the plugin suddenly disappear while I do my mining, if each time i have to do factory reset then it going to be very annoying. I will close the thread and be more careful not to bother you again :vv Thank for your hard work.

**Comment by nairyosangha** [comment]
You shouldn't ever have to do a factory reset honestly, if it happens again, please just post your crash.log because they're probably will be a hint in there as to what went wrong
