### ISSUE TITLE
Timeout 

### ISSUE THREAD

**Issue by kippostea** [Ajatt-Tools/anki.koplugin#37]
Hey there, I've followed the instructions of changing the AnkiConnect webBindAddress to 0.0.0.0 and inputted my IPv4 address into the "config.lua" file but I am still getting the "Synchronizing failed! Unable to reach AnkiConnect. timeout." message, I am unsure of what to do now. Any help would be appreciated!

**Comment by nairyosangha** [comment]
Going by past issues, timeout usually indicates you filled in a wrong IP, how did you figure out what your local IP address is? If your e-reader has a browser, does going to `http://<IP ADDRESS HERE>:8765` resolve?

**Comment by nairyosangha** [comment]
maybe check the comments in this issue as well https://github.com/Ajatt-Tools/anki.koplugin/issues/2#issuecomment-1489194210

**Comment by kippostea** [comment]
I went into Command Prompt to and put in ipconfig to find my IPv4 address. I'm using a Kobo Libra Color that somewhat has a browser built it. However, when I input the http address into the browser, nothing happens. When I input it on my desktop it sends me to the site that says "AnkiConnect v.6"

**Comment by nairyosangha** [comment]
> However, when I input the http address into the browser, nothing happens

So it's probably timing out there as well, that's consistent at least.

> When I input it on my desktop it sends me to the site that says "AnkiConnect v.6"

Great so something is working right, I assume this is the computer that's running Anki? Does the HTTP address resolve from your phone or any other PC? Did you also restart Anki after making that change? I would guess so since otherwise the URL probably wouldn't resolve even on the desktop itself, unless you put it 127.0.0.1 as address

**Comment by kippostea** [comment]
Yes it is the computer that's running Anki. I tried it on my phone and it timed out on there. So I assume it's only working on the localhost. Could it be that I would need to forward the port 8765? 

I use Anki on multiple different devices, would that affect anything?

**Comment by kippostea** [comment]
Ahh that's right, I used the wrong IPv4 address. It is now working! I appreciate the help!
