### ISSUE TITLE
Crashing after 'Add to Anki'

### ISSUE THREAD

**Issue by anaxonda** [Ajatt-Tools/anki.koplugin#40]
Before creating an issue, please check if you're using the most up-to-date version of the plugin! Reinstall it if necessary.

* KOReader version: 202411

**Describe the Issue**
Crashing while trying to add any note to Anki 

**How to Reproduce (if relevant)**
Attempt to 

**crash.log**
````
11/27/24-19:51:42 INFO  AnkiNote#get_custom_context() 1 0 1 0
./luajit: common/socket/http.lua:278: attempt to index local 'schemedefs' (a nil value)
stack traceback:
	[C]: in function 'func'
	plugins/anki.koplugin/ankiconnect.lua:25: in function 'with_timeout'
	plugins/anki.koplugin/ankiconnect.lua:34: in function 'is_running'
	plugins/anki.koplugin/ankiconnect.lua:243: in function 'add_note'
	plugins/anki.koplugin/main.lua:277: in function 'set_profile'
	plugins/anki.koplugin/main.lua:275: in function 'callback'
	frontend/ui/widget/buttontable.lua:81: in function 'callback'
	frontend/ui/widget/button.lua:473: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:266: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/uimanager.lua:911: in function 'sendEvent'
	frontend/ui/uimanager.lua:53: in function '__default__'
	frontend/ui/uimanager.lua:1438: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1538: in function 'handleInput'
	frontend/ui/uimanager.lua:1582: in function 'run'
	./reader.lua:280: in main chunk

````

**Additional context**
I'm not sure whats going on. I've copied latest version over, identical except for a 'default.lua
 profile that is the same as the one provided, except with my AnkiConnect address. 

- first tried to make a note with wifi turned off. This failed. 
- I went and deleted the old local notes json in koreader/settings
- Tried to make offline anki note again, success.
- Turned on wifi. Now every time koreader crashes with the log above, wifi on or off. There is no local notes json file in koreader/settings directory.

Hope there is something easy i'm overlooking.

**Comment by nairyosangha** [comment]
Ah no, that's not it, you probably didn't specify the `http://` prefix at all, I should probably add a check for that since the error that's there now is pretty cryptic

**Comment by anaxonda** [comment]
Ah, that was it. I was sure it was something stupid.
