### ISSUE TITLE
Crashes after trying to add more than 1 word in a session

### ISSUE THREAD

**Issue by squishygian** [Ajatt-Tools/anki.koplugin#44]
Hello again 😔,

I'ts been awhile, suffice to say I was enjoying using this plugin and studying my anki note cards, all that changed today, I got a new e-ink device, specifically the Hisense a9, I rooted it to Android 14 and installed Koreader, then I thought, why don't I go ahead and install my favorite Koreader plugin 😃, I downloaded the code, extracted it, changed the fields to match my anki note style, as I mainly use this for English vocab on basic style notes, and OK let's go ahead and give it a try, first word gets added to the deck no problem, wow that was easy! let's try it again, 2nd note gets this error:

![Screenshot_20241228-214316.png](https://github.com/user-attachments/assets/330ea8ac-9ec5-468e-a849-99391ccd2b62)

Hmmm that's odd, let's restart the app and try again, first word goes through, 2nd word gets the error, thus began a long string of troubleshooting to no success, here is a succinct list of some of things I tried:

-Different document/dictionary/language/anki deck

-Restart anki connect in-between each word

-Removing or changing every field in the profile.lua file that wouldn't actually break the plugin

-and finally adding them offline and then trying to sync them online

But time after time the same thing kept happening, the first word would get added fine and the 2nd would cause the plugin to display that error and not work anymore, so I am in dire need of some help and appreciate any input, thank you so much for all your hard work and dedication to this plugin, let me know if there's any more info you need, thank you!

**Comment by nairyosangha** [comment]
Hello,

I'd like to see your crash.log, with debug logging turned on. It seems to be failing when it's trying to check whether AnkiConnect is running. It's odd that it complains about a malformed JSON there, all we do there is check that `http://localhost:8765/` (or whatever IP you're using) returns a 200 response. I don't get why it would work the first time, but then after saving one note it suddenly wouldn't anymore. It makes me think that saving the first note breaks something in that AnkiConnect implementation you're using


I'm also curious if you can see logs of that ankiconnect program itself, that's something you have to run manually on your phone right, does that log anything?

**Comment by squishygian** [comment]
Interesting, how do I see the crash log?

**Comment by nairyosangha** [comment]
I put info on how to get it in the issue template:

**crash.log**
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please provide the crash.log even when KOreader did not actually crash! It usually contains the necessary information to ascertain what went wrong.

**Comment by squishygian** [comment]
OK I enabled the crash log, the only thing is it doesn't update when the anki plugin crashes, I think because Koreader doesn't crash, so IDK how useful this is to you:

--------- beginning of crash
12-28 23:33:12.555 F/libc    (12624): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10 in tid 12644 (Thread-502), pid 12624 (reader.launcher)
12-29 00:48:46.814 F/libc    (15081): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10 in tid 15104 (Thread-423), pid 15081 (reader.launcher)
--------- beginning of main
12-29 15:07:40.129 V/NativeGlue(20918): Start: 0xb4000071b1a53030
12-29 15:07:40.144 D/MainActivity(20918): onNewIntent(): null
12-29 15:07:40.149 V/NativeGlue(20918): Resume: 0xb4000071b1a53030
12-29 15:07:40.150 V/Timeout (20918): onResume: updating system timeout: 1
12-29 15:07:40.150 V/Timeout (20918): onResume
12-29 15:07:40.166 V/NativeGlue(20918): NativeWindowCreated: 0xb4000071b1a53030 -- 0xb400007191a252b0
12-29 15:07:40.176 I/MainActivity(20918): New intent: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10600000 cmp=org.koreader.launcher/.MainActivity }.action
12-29 15:07:40.176 W/KOReader(20918): cannot blit: no window
12-29 15:07:40.177 V/Surface (20918): surface changed {
12-29 15:07:40.177 V/Surface (20918):   width:  824
12-29 15:07:40.177 V/Surface (20918):   height: 1648
12-29 15:07:40.177 V/Surface (20918):   format: OPAQUE
12-29 15:07:40.177 V/Surface (20918): }
12-29 15:07:40.177 V/NativeGlue(20918): NativeWindowResized: 0xb4000071b1a53030 -- 0xb400007191a252b0
12-29 15:07:40.178 V/NativeGlue(20918): NativeWindowRedrawNeeded: 0xb4000071b1a53030 -- 0xb400007191a252b0
12-29 15:07:40.208 V/NativeGlue(20918): WindowFocusChanged: 0xb4000071b1a53030 -- 1
12-29 15:07:47.700 W/KOReader(20918): command sh -c test -x bash || command -v bash returned 1
12-29 15:07:47.700 V/KOReader(20918):  stdout: 
12-29 15:07:47.700 V/KOReader(20918):  stderr: 
12-29 15:07:47.712 W/KOReader(20918): command sh -c test -x ash || command -v ash returned 1
12-29 15:07:47.712 V/KOReader(20918):  stdout: 
12-29 15:07:47.712 V/KOReader(20918):  stderr: 
12-29 15:07:47.721 I/KOReader(20918): command sh -c test -x sh || command -v sh returned 0
12-29 15:07:47.722 V/KOReader(20918):  stdout: /system/bin/sh
12-29 15:07:47.722 V/KOReader(20918): 
12-29 15:07:47.722 V/KOReader(20918):  stderr:

**Comment by nairyosangha** [comment]
Yeah that log indeed isn't helpful.
I tried getting the logs myself, I installed KOreader and that AnkiConnect Android implementation on my phone, and managed to reproduce it:

```logs
12-30 13:44:05.477 19860 17987 D AnkiConnectAndroid: received json: URL was not validated yet, we should not get here
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: Error: com.google.gson.JsonSyntaxException : com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6 path $
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6 path $
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at com.google.gson.JsonParser.parseReader(JsonParser.java:66)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at com.google.gson.JsonParser.parseString(JsonParser.java:47)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at com.kamwithk.ankiconnectandroid.request_parsers.Parser.parse(Parser.java:25)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at com.kamwithk.ankiconnectandroid.routing.APIHandler.chooseAPI(APIHandler.java:32)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at com.kamwithk.ankiconnectandroid.routing.RouteHandler.get(RouteHandler.java:70)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at fi.iki.elonen.router.RouterNanoHTTPD$DefaultStreamHandler.post(RouterNanoHTTPD.java:100)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at fi.iki.elonen.router.RouterNanoHTTPD$UriResource.process(RouterNanoHTTPD.java:386)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at fi.iki.elonen.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:596)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at fi.iki.elonen.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:671)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at java.lang.Thread.run(Thread.java:919)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6 path $
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1597)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1404)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	at com.google.gson.JsonParser.parseReader(JsonParser.java:61)
12-30 13:44:05.488 19860 17987 E RouterNanoHTTPD: 	... 11 more
12-30 13:44:05.489 17693 17718 V KOReader: AnkiConnect#is_running = code: 500, headers: table: 0x756a8e3098, result: Error: com.google.gson.JsonSyntaxException : com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6 path $
```

First line immediately showed me the issue, it's indeed passing in an invalid JSON, it shouldn't be passing that string along at all. I've pushed a change that fixes the problem for me (https://github.com/Ajatt-Tools/anki.koplugin/commit/95a9a4095876cf60cd247267cdc81e3afdc9a22a), could you give that a try?

In case you're wondering how to get those logs, I basically just followed what's listed here: https://www.airdroid.com/mdm/view-android-logs/

I learned something new today :D

**Comment by squishygian** [comment]
YESSSS IT WORKS AGAIN!!! THANK YOUUUUUUU
