### ISSUE TITLE
Sentences are sent to context_field without spaces

### ISSUE THREAD

**Issue by YashaNoos** [Ajatt-Tools/anki.koplugin#6]
Hello again!
I have noticed that the new versions (from May 18 and up) of the plugin suppress spaces in sentences sent to  context_field.

Apr 16:
<img width="940" alt="anki_kRIAOd8bcc" src="https://github.com/Ajatt-Tools/anki.koplugin/assets/109368517/5101e1e8-4c02-480d-bb02-498a8a498c3c">

May 18:
<img width="945" alt="anki_FnhPGpndNk" src="https://github.com/Ajatt-Tools/anki.koplugin/assets/109368517/1bd8a432-f44f-4081-968e-97b4746d212c">

I guess it has something to do with the "custom sentence context" addition (pretty cool feature btw).
Thanks again for your work, your plugin make my workflow SO much more streamlined.

**Comment by nairyosangha** [comment]
Oops, I should have checked with against a language that actually uses whitespaces meaningfully. Should be fixed with this https://github.com/Ajatt-Tools/anki.koplugin/commit/7df6b5f4c1d02a3f6045c26ff9ff7f19e852d1cb

**Comment by YashaNoos** [comment]
Just tested it, works perfectly now! 
<img width="942" alt="anki_mir9IMrzno" src="https://github.com/Ajatt-Tools/anki.koplugin/assets/109368517/95db3f02-3343-4213-afaa-14b4f556bb63">
And the forvo audio is now automatically downloaded \o/
Thanks for your quick response have a nice day!
