### ISSUE TITLE
Connecting Anki to Koreader in Android

### ISSUE THREAD

**Issue by unacceptablet** [Ajatt-Tools/anki.koplugin#8]
Greetings!

My device: Onyx Boox Leaf 2 (android 11)

I have installed a Koreader plugin using this tutorial guide: https://github.com/Ajatt-Tools/anki.koplugin
Then I installed [AnkiconnectAndroid](https://github.com/KamWithK/AnkiconnectAndroid), put http://localhost:8765/ in CORS Host settings, start service. When I press add to anki in Koreader, I get these errors:

![image](https://github.com/KamWithK/AnkiconnectAndroid/assets/127971612/670e6f6c-5830-43e6-a30b-dbcced961390)

Any solutions?

**Comment by nairyosangha** [comment]
This looks like a bug in that AnkiConnect implementation you're using, judging by the stacktrace.
I'd tell you to ask them, but looks like you already did :smile:
